"""ReportMCP server — save_report tool.

Used by Supervisor for saving reports (HITL gated at supervisor level).
Run: python mcp_servers/report_mcp.py  (port 8902)
"""

import json
import logging
import os
import sys
from datetime import datetime
from logging.handlers import RotatingFileHandler
from pathlib import Path

from fastmcp import FastMCP

sys.path.insert(0, str(Path(__file__).parent.parent))

from config import Settings  # noqa: E402

Path("logs").mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
    handlers=[
        logging.StreamHandler(),
        RotatingFileHandler("logs/report_mcp.log", maxBytes=5_000_000, backupCount=3),
    ],
)
logger = logging.getLogger("report_mcp")

settings = Settings()
mcp = FastMCP("ReportMCP")


@mcp.tool
def save_report(filename: str, content: str) -> str:
    """Save a Markdown research report to the output directory."""
    try:
        os.makedirs(settings.output_dir, exist_ok=True)
        if not filename.endswith(".md"):
            filename += ".md"
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M")
        full_name = f"{timestamp}_{filename}"
        filepath = os.path.join(settings.output_dir, full_name)
        meta = f"> Generated by Multi-Agent Research System on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(meta + content)
        logger.info("Report saved: %s", filepath)
        return f"Report saved successfully to: {filepath}"
    except Exception as e:
        return f"Error saving report: {e}"


@mcp.resource("resource://output-dir")
def output_dir_info() -> str:
    """List saved reports in the output directory."""
    output = Path(settings.output_dir)
    if not output.exists():
        return json.dumps({"path": str(output), "reports": []})
    files = sorted(
        (f.name for f in output.glob("*.md") if f.name[:1].isdigit()),
        reverse=True,
    )
    return json.dumps({"path": str(output), "reports": files})


if __name__ == "__main__":
    mcp.run(transport="http", host="0.0.0.0", port=settings.report_mcp_port)  # noqa: S104
